name: Share data between jobs

on: [push]
jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - name:  see
        shell: bash
        run: |
          MLPACK_VERSION_VALUE=3.2.3
          echo ::set-output name=mlpack_r_bin::$(echo mlpack_"$MLPACK_VERSION_VALUE".tar.gz)
          expr 3 + 7 > math-${{ steps.see.outputs.mlpack_r_bin }}.txt
          echo mlpack_${{ steps.see.outputs.mlpack_r_bin }}.tar.gz
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-${{ steps.see.outputs.mlpack_r_bin }}.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat math-${{ steps.see.outputs.mlpack_r_bin }}.txt`
          expr $value \* 9 > math-${{ steps.see.outputs.mlpack_r_bin }}.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
